"""R5 — E5 comparator: DSR batch (3차 M9 대응).

E5와 동일한 mixed queue/timing world를 공통난수(CRN)로 재생성한다. 각 런 종료
시점 T=360에서 BLdP(2014) deflated Sharpe ratio를 batch family 검정으로 실행하고,
anytime protocol의 E5 분해표와 power/delay를 비교한다.

실행: MPLBACKEND=Agg python3 -m sim.run_R5
"""
import time

import numpy as np
import pandas as pd
from scipy import stats

from . import common, eprocess as ep, world
from .run_E5 import ALPHA, DL, J_BUDGET, LAM_ARR, M_ENV, N_RUN, P_ALT, T

EULER_GAMMA = 0.5772156649015329


def regenerate_e5_world(lam: float, run_idx: int) -> dict[str, np.ndarray | int]:
    """E5의 등록 및 score 생성부를 동일 난수 순서로 재생성."""
    rng = common.rng_for(common.EXP_ID["E5"], int(lam * 10), run_idx)
    d_star = float(ep.frontier.catoni[1])              # delta*(120)

    # run_E5.run_one과 동일 추첨 순서 (CRN): counts -> arrivals -> A -> is_alt -> eps -> Ymat
    counts = rng.poisson(lam, T)
    arrivals = np.repeat(np.arange(T), counts)
    n_arrived = len(arrivals)
    A = arrivals[:J_BUDGET]
    budget_exh_month = int(arrivals[J_BUDGET - 1]) if n_arrived >= J_BUDGET else -1
    J = len(A)
    is_alt = rng.random(J) < P_ALT

    lens = np.minimum(DL, T - 1 - A)
    eps = world.draw_eps(rng, J, DL, noise="gaussian")
    Ymat = np.zeros((J, DL))
    for j in range(J):
        Ymat[j, :lens[j]] = eps[j, :lens[j]] + (d_star if is_alt[j] else 0.0)
    return {"A": A, "is_alt": is_alt, "lens": lens, "Ymat": Ymat,
            "n_arrived": n_arrived, "n_reg": J,
            "budget_exh_month": budget_exh_month}


def dsr_discoveries(Ymat: np.ndarray, lens: np.ndarray, n_reg: int,
                    alpha: float = ALPHA) -> tuple[np.ndarray, int, int]:
    """BLdP(2014) DSR batch 발견 플래그."""
    disc = np.zeros(n_reg, bool)
    family = lens >= 2
    excluded_short = int((~family).sum())
    idx = np.nonzero(family)[0]
    if n_reg < 2 or len(idx) < 2:
        return disc, excluded_short, int(len(idx))

    sr = np.empty(len(idx))
    g3 = np.empty(len(idx))
    g4 = np.empty(len(idx))
    for out_i, j in enumerate(idx):
        y = Ymat[j, :lens[j]]
        n_i = len(y)
        m1 = float(y.mean())
        centered = y - m1
        m2 = float((centered ** 2).mean())
        assert m2 > 0.0, "DSR sd 정의 불가 경로 발생"
        m3 = float((centered ** 3).mean())
        m4 = float((centered ** 4).mean())
        sr[out_i] = m1 / np.sqrt(m2 * n_i / (n_i - 1))
        g3[out_i] = m3 / (m2 ** 1.5)
        g4[out_i] = m4 / (m2 ** 2)

    V = float(np.var(sr, ddof=1))
    sr0 = np.sqrt(V) * (
        (1 - EULER_GAMMA) * stats.norm.ppf(1 - 1 / n_reg)
        + EULER_GAMMA * stats.norm.ppf(1 - 1 / (n_reg * np.e))
    )
    denom = np.clip(1 - g3 * sr + (g4 - 1) / 4 * sr ** 2, 1e-12, None)
    z = (sr - sr0) * np.sqrt(lens[idx] - 1) / np.sqrt(denom)
    disc[idx] = stats.norm.cdf(z) > 1 - alpha
    return disc, excluded_short, int(len(idx))


def assert_crn(group: pd.DataFrame, lam: float, run_idx: int,
               A: np.ndarray, is_alt: np.ndarray) -> None:
    """저장된 E5 전략 메타와 재생성된 A/is_alt 완전 일치를 확인."""
    got_A = group["A"].to_numpy()
    got_alt = group["is_alt"].to_numpy(dtype=bool)
    assert len(got_A) == len(A), f"CRN 길이 불일치: lam={lam}, run={run_idx}"
    assert np.array_equal(got_A, A), f"CRN A 불일치: lam={lam}, run={run_idx}"
    assert np.array_equal(got_alt, is_alt), f"CRN is_alt 불일치: lam={lam}, run={run_idx}"


def format_num(x: float, digits: int = 1) -> str:
    """표 출력용 숫자 포맷."""
    return "NA" if pd.isna(x) else f"{x:.{digits}f}"


def format_pct(x: float) -> str:
    """작은 검출률을 0.0%로 숨기지 않는 비율 포맷."""
    if pd.isna(x):
        return "NA"
    pct = 100 * x
    return f"{pct:.3f}%" if 0 < abs(pct) < 0.1 else f"{pct:.1f}%"


def format_pct_tex(x: float) -> str:
    """LaTeX 표용 비율 포맷."""
    return format_pct(x).replace("%", "\\%")


def write_tex(comp: pd.DataFrame) -> None:
    """R5 비교표 LaTeX 파일 생성."""
    lines = [
        "% Rev3 M9 -- E5 protocol vs batch DSR comparator (auto-generated by sim/run_R5.py)",
        "\\begin{table}[htbp]",
        "\\centering\\small",
        "\\caption{E5 anytime protocol versus terminal batch DSR comparator.}",
        "\\label{tab:rev3-m9-dsr}",
        "\\begin{tabular}{ccccc}",
        "\\toprule",
        "$\\lambda_{\\rm arr}$ & Protocol power & Protocol mean delay & DSR power & DSR mean delay \\\\",
        "\\midrule",
    ]
    for row in comp.itertuples(index=False):
        lines.append(
            f"{row.lam_arr:.1f} & {format_pct_tex(row.protocol_power)} & "
            f"{row.protocol_mean_delay:.1f} & {format_pct_tex(row.dsr_power)} & "
            f"{format_num(row.dsr_mean_delay, 1)} \\\\"
        )
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\begin{minipage}{0.92\\linewidth}",
        "\\footnotesize",
        "Notes: DSR discoveries are available only at the terminal batch time $T=360$, "
        "so DSR delay is defined as $T-A_j$; the protocol is anytime/sequential, and "
        "the delay definitions reflect the procedures themselves. SPA (Hansen 2005) "
        "and White's Reality Check (2000) are max-over-strategies tests relative to a "
        "benchmark, do not provide per-strategy certification, and have no anytime "
        "operation here; they are outside this comparison scope and are not run. The "
        "DSR comparator is idealized by giving it the exogenous trial count "
        "$N=n_{\\rm reg}$.",
        "\\end{minipage}",
        "\\end{table}",
        "",
    ])
    path = common.REPO / "review" / "appendix_rev3_m9.tex"
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> pd.DataFrame:
    t0 = time.time()
    strat_path = common.RESULTS / "E5_strategies.parquet"
    decomp_path = common.RESULTS / "E5_decomp.parquet"
    e5_strat = pd.read_parquet(strat_path)
    e5_decomp = pd.read_parquet(decomp_path)
    groups = e5_strat.groupby(["lam_arr", "run_id"], sort=False)

    rows = []
    delay_rows = []
    checked = 0
    for lam in LAM_ARR:
        tc = time.time()
        for run_idx in range(N_RUN):
            world_e5 = regenerate_e5_world(lam, run_idx)
            group = groups.get_group((lam, run_idx))
            A = world_e5["A"]
            is_alt = world_e5["is_alt"]
            lens = world_e5["lens"]
            Ymat = world_e5["Ymat"]
            n_reg = int(world_e5["n_reg"])
            assert_crn(group, lam, run_idx, A, is_alt)
            checked += 1

            disc, excluded_short, family_size = dsr_discoveries(Ymat, lens, n_reg)
            alt_disc = disc & is_alt
            false_disc = disc & ~is_alt
            delays = (T - A[alt_disc]).astype(int)
            for delay in delays:
                delay_rows.append({"lam_arr": lam, "delay": int(delay)})
            n_disc = int(disc.sum())
            n_false = int(false_disc.sum())
            rows.append({"lam_arr": lam, "run_id": run_idx,
                         "n_arrived": int(world_e5["n_arrived"]),
                         "n_reg": n_reg,
                         "budget_exh_month": int(world_e5["budget_exh_month"]),
                         "n_alt": int(is_alt.sum()),
                         "family_size": family_size,
                         "excluded_short": excluded_short,
                         "dsr_n_disc": n_disc,
                         "dsr_n_false": n_false,
                         "dsr_alt_disc": int(alt_disc.sum()),
                         "dsr_fdp": n_false / max(n_disc, 1),
                         "dsr_alt_delay_mean": float(delays.mean()) if len(delays) else np.nan,
                         "dsr_alt_delay_median": float(np.median(delays)) if len(delays) else np.nan})
        print(f"  lam_arr={lam}: CRN 확인 + DSR 완료 ({time.time() - tc:.0f}s)",
              flush=True)

    print(f"CRN 게이트 통과: E5_strategies.parquet의 A/is_alt 전 {checked}런 완전 일치")
    df = pd.DataFrame(rows)
    path = common.write_parquet(df, "R5.parquet")
    delay_df = pd.DataFrame(delay_rows)

    comp_rows = []
    for lam in LAM_ARR:
        sub = df[df["lam_arr"] == lam]
        proto = e5_decomp[e5_decomp["lam_arr"] == lam].iloc[0]
        d = delay_df[delay_df["lam_arr"] == lam]["delay"] if len(delay_df) else pd.Series(dtype=float)
        total_alt = int(sub["n_alt"].sum())
        total_disc = int(sub["dsr_n_disc"].sum())
        comp_rows.append({"lam_arr": lam,
                          "protocol_power": float(proto["alt_det_rate"]),
                          "protocol_mean_delay": float(proto["total_mean"]),
                          "dsr_power": float(sub["dsr_alt_disc"].sum() / max(total_alt, 1)),
                          "dsr_mean_delay": float(d.mean()) if len(d) else np.nan,
                          "dsr_median_delay": float(d.median()) if len(d) else np.nan,
                          "dsr_fdp_mean": float(sub["dsr_fdp"].mean()),
                          "dsr_null_share": float(sub["dsr_n_false"].sum() / max(total_disc, 1)),
                          "dsr_n_disc": total_disc,
                          "dsr_n_false": int(sub["dsr_n_false"].sum())})
    comp = pd.DataFrame(comp_rows)
    write_tex(comp)

    print("\nR5 protocol vs DSR batch 비교:")
    for row in comp.itertuples(index=False):
        print(f"  λ={row.lam_arr:.1f}: protocol power={row.protocol_power:.6f} "
              f"({format_pct(row.protocol_power)}), "
              f"delay={row.protocol_mean_delay:.1f}; "
              f"DSR power={row.dsr_power:.6f} ({format_pct(row.dsr_power)}), "
              f"delay mean={format_num(row.dsr_mean_delay)}, "
              f"delay median={format_num(row.dsr_median_delay)}, "
              f"FDP(mean run)={row.dsr_fdp_mean:.6f}, "
              f"null share(total)={row.dsr_null_share:.6f}, "
              f"DSR false/disc={row.dsr_n_false}/{row.dsr_n_disc}")
    print(f"\nR5 완료 (총 {time.time() - t0:.0f}s, commit {common.commit_hash()})")
    print(f"saved -> {path.name}, review/appendix_rev3_m9.tex")
    return df


if __name__ == "__main__":
    main()
